### ISSUE TITLE
Failed to the program locally

### ISSUE THREAD

**Issue by hargup** [vignshwarar/AI-Employe#2]
Getting following error on `localhost:3000`

<img width="996" alt="Screenshot 2023-12-27 at 4 11 56 PM" src="https://github.com/vignshwarar/AI-Employe/assets/2477788/3fed1158-73ac-4625-9633-dd380ab436e0">

**Comment by vignshwarar** [comment]
I just downloaded the repo and checked on my system that it is working. Could you please try these steps:

- Go to 'cd client/web', delete the '.next' and 'node_modules' folders, then reinstall 'node_modules' by typing 'npm install' in the 'client/web' directory. After that, try running 'npm run dev' in the same 'client/web' directory.
- Ensure that you have '.env.development' file. You can simply copy and paste '.env.sample' as '.env.development'.

It appears to be a transpiling issue. Could you confirm the version of Next.js that is installed?

**Comment by hargup** [comment]
Okay

- added the firebase keys
- removed node modules and recompiled
- Commented out part of the code which required `Crisp`

Current behavior:
- Seeing the sign-up page, but the signup is not happening
https://www.loom.com/share/d58a6886643d482b82f455b27a1179dd

Ideally, local development shouldn't require signups. Will see, if I feel motivated enough, might make a PR to make the local development entirely local.

**Comment by vignshwarar** [comment]
> Ideally, local development shouldn't require signups

True, will try to make a PR

> Seeing the sign-up page, but the signup is not happening

Could you please post the error message from the Chrome console or the server log?

**Comment by hargup** [comment]
Still not working, console error
```
vendor-a1b7b07f-59a0e76009756a5473ca.js:15 No storage available for session. We will not send any data.
(anonymous) @ vendor-a1b7b07f-59a0e76009756a5473ca.js:15
chrome-extension://invalid/:1 
        
        
       Failed to load resource: net::ERR_FAILED
vendor-a1b7b07f-59a0e76009756a5473ca.js:15 Shaka Player's internal Manifest structure is NOT covered by semantic versioning compatibility guarantees.  It may change at any time!  Please consider filing a feature request for whatever you use getManifest() for.
(anonymous) @ vendor-a1b7b07f-59a0e76009756a5473ca.js:15
vendor-9ebd23ae-97bc16e20d0d6d0d326d.js:1 WebSocket connection to 'wss://www.loom.com/graphql' failed: WebSocket is closed before the connection is established.
e.close @ vendor-9ebd23ae-97bc16e20d0d6d0d326d.js:1
identitytoolkit.googleapis.com/v1/projects?key=<key>:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
SignIn.tsx:97 FirebaseError: Firebase: Error (auth/configuration-not-found).
    at createErrorInternal (index-dd468b12.js:615:41)
    at _fail (index-dd468b12.js:586:11)
    at _performFetchWithErrorHandling (index-dd468b12.js:1051:17)
    at async _validateOrigin (index-dd468b12.js:9648:35)
www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=<key>&cb=1704665619402:1 

       Failed to load resource: the server responded with a status of 400 ()

```        

![Uploading Screenshot 2024-01-08 at 3.45.27 AM.png…]()

**Comment by hargup** [comment]
using the latest commit here

**Comment by vignshwarar** [comment]
Thank you for the screenshot.

I created a branch without an auth: https://github.com/vignshwarar/AI-Employe/tree/remove_auth 
- Make sure to setup DEPLOYMENT_TYPE="open-source": https://github.com/vignshwarar/AI-Employe/blob/remove_auth/.env.sample#L30
- and MEILISEARCH_API_KEY, DATABASE_URL
- cd into ```client/extension``` and run ```npm run dev``` drop the build folder to chrome extension ```chrome://extensions```
- cd into ```server``` and run ```npm run dev```

This is a bit annoying, but it will make it easier.

Regarding your Firebase error, I think you have to turn on Google auth or Email auth option: https://stackoverflow.com/a/70738662/5947166

**Comment by rothnic** [comment]
@vignshwarar Trying to get this working locally as well. It is hard to tell which entries in the .env.development file are required or not when running in dev mode. In dev mode it still seems to require all these:

```
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
```

From the readme and the discussion above, i got the impression they weren't required if using the `open-source` and dev mode. These all look firebase-like, but not sure exactly what they are mapped to.

<img width="972" alt="image" src="https://github.com/vignshwarar/AI-Employe/assets/452052/aa7a7693-48a8-4298-9968-9843b709dd24">

**Comment by rothnic** [comment]
Well, I got it kind of working after doing the following:

* set `NEXT_PUBLIC_API_KEY="firebase web api key from settings page"`
* set `NEXT_PUBLIC_PROJECT_ID="firebase project id"`
* created a bucket in the storage area of firebase, then set `NEXT_PUBLIC_STORAGE_BUCKET="gs://<firebase_project_id>.appspot.com/<bucket_name>"`
*  set NEXT_PUBLIC_MESSAGING_SENDER_ID and NEXT_PUBLIC_APP_ID to firebase "Project number"
* commented out Crisp in _app.tx
* enabled email auth with login link support in firebase authentication section

I'm able to get into the app, but it just points me to installing the extension. I installed the extension from the build folder, but it doesn't seem to do anything. I also don't see any output when inspecting the service worker. Any ideas for getting the extension to work?

**Comment by vignshwarar** [comment]
The console error does not seem to be related to AI Employe, and the .tui-image-editor-main-container appears to be an image editor library.

2 things:
- Have you build the extension and installed it?
- What is happening when you click the extension icon?

**Comment by rothnic** [comment]
Ah ok, yeah didn't look to see if it was another extension. Yeah, I built it and installed and it doesn't do anything when clicked.

**Comment by vignshwarar** [comment]
Could you please check the service worker logs after clicking the extension?

Reference image:
<img width="413" alt="Screenshot 2024-01-18 at 5 00 35 PM" src="https://github.com/vignshwarar/AI-Employe/assets/64212638/eb91c47d-828b-45ff-8413-e9e489393b25">

**Comment by rothnic** [comment]
> Could you please check the service worker logs after clicking the extension?

Yeah that was what I first mentioned looking at. There isn't a single bit of activity I see associated with the service worker.

**Comment by rothnic** [comment]
Here is the extension if you want to try it:
[roth_extension_build.zip](https://github.com/vignshwarar/AI-Employe/files/13979638/roth_extension_build.zip)

**Comment by vignshwarar** [comment]
This is weird. Could you please open the sidebar and check whether the 'AI employee' icon is on the list or not? I will check your zip file when I get back to my system.

Reference image for sidebar:
<img width="409" alt="Screenshot 2024-01-18 at 6 23 25 PM" src="https://winaero.com/blog/wp-content/uploads/2023/05/Google-Chrome-Customize-Sidebar-001.png">

**Comment by rothnic** [comment]
Interesting... so I have been using the Arc browser, which I haven't had any extension issues with. I see the icon and it does nothing in Arc, but tried it in Chrome and got it to pop up on the right on click. Sorry for the confusion. Didn't realize that could be a potential issue.

I did have a list of other things I had to work through and fix to get this working locally and I'll share that once I verify I get it working completely. Mainly it was working through errors related to dependencies that weren't managed explicitly in the readme.

**Comment by rothnic** [comment]
Here is the output from the console for the service worker and ui.html, respectively:

<img width="873" alt="image" src="https://github.com/vignshwarar/AI-Employe/assets/452052/709b75b6-e13c-470d-a835-67b707ec6b62">

<img width="1041" alt="image" src="https://github.com/vignshwarar/AI-Employe/assets/452052/5cbfe419-ba67-4882-a700-a1e3b75feca3">

**Comment by shali1995** [comment]
has anyone managed to make it work?

**Comment by rothnic** [comment]
I was able to generally get it "working", but overall had issues getting a workflow that actually did what I wanted it to. I ended up going down the path of building my own chrome extension. 

What issues do you have? I could dig up that project folder and share what state I left it in, but think overall it just had some dependency issues I had to resolve to get it working.

**Comment by shali1995** [comment]
> I was able to generally get it "working", but overall had issues getting a workflow that actually did what I wanted it to. I ended up going down the path of building my own chrome extension.
> 
> What issues do you have? I could dig up that project folder and share what state I left it in, but think overall it just had some dependency issues I had to resolve to get it working.

would be happy to use your extention, can i try?

**Comment by rothnic** [comment]
Oh, the one I was working on was more tailored to a specific use case and less about teaching the extension how to do something. One option to look at that is more in line with what I was doing in terms of controlling and interacting with a real browser (non headless) is a project called opendia. I'm going to start contributing to it.
